import{useEffect,useState}from'react';import{parentsApi,studentsApi,type Parent,type Student}from'../api/system';import{Icon}from'../components/Icon';import{useMessage}from'../context/MessageContext';
type Form={email:string;password:string;firstName:string;lastName:string;gender:string;address:string;phoneNumber:string};const empty:Form={email:'',password:'',firstName:'',lastName:'',gender:'MALE',address:'',phoneNumber:''};
export function ParentsPage(){const{showError}=useMessage();const[rows,setRows]=useState<Parent[]>([]),[students,setStudents]=useState<Student[]>([]),[children,setChildren]=useState<Student[]>([]),[selected,setSelected]=useState<Parent|null>(null),[form,setForm]=useState<Form>(empty),[open,setOpen]=useState(false),[linkId,setLinkId]=useState('');
const load=async()=>{try{const[p,s]=await Promise.all([parentsApi.all(),studentsApi.all()]);setRows(p.slice().sort((a,b)=>`${a.firstName} ${a.lastName}`.localeCompare(`${b.firstName} ${b.lastName}`)));setStudents(s);}catch{showError('Could not load parents.');}};useEffect(()=>{void load();},[]);const inspect=async(p:Parent)=>{setSelected(p);setChildren(await parentsApi.children(p.id));};
const edit=(p:Parent)=>{setSelected(p);setForm({email:p.email,password:'',firstName:p.firstName,lastName:p.lastName,gender:p.gender??'MALE',address:p.address??'',phoneNumber:p.phoneNumber??''});setOpen(true);};
const save=async()=>{try{selected?await parentsApi.update(selected.id,form):await parentsApi.create(form);setOpen(false);setSelected(null);setForm(empty);await load();}catch{showError('Parent could not be saved.');}};
return <div><div className="breadcrumb">Home › <span className="current">Parents</span></div><div className="split-view"><div className="panel"><div className="panel-header"><div className="panel-icon"><Icon name="family" /></div><div><div className="panel-eyebrow">Families</div><h3>Parent accounts</h3></div></div><div className="filter-bar"><button className="btn-primary" onClick={()=>{setSelected(null);setForm(empty);setOpen(true);}}>Add parent</button></div><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.firstName} {p.lastName}</td><td>{p.email}</td><td><div className="row-actions"><button className="btn-text" onClick={()=>void inspect(p)}>Children</button><button className="btn-text" onClick={()=>edit(p)}>Edit</button></div></td></tr>)}</tbody></table></div>
<div className="panel" style={{padding:22}}>{selected?<><h3>{selected.firstName} {selected.lastName}</h3><div className="field"><label>Link student</label><select value={linkId} onChange={e=>setLinkId(e.target.value)}><option value="">Select student</option>{students.filter(s=>!children.some(c=>c.id===s.id)).map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName}</option>)}</select></div><button className="btn-primary" disabled={!linkId} onClick={async()=>{await parentsApi.link(selected.id,Number(linkId));setLinkId('');await inspect(selected);}}>Link child</button><div style={{marginTop:18}}>{children.map(c=><div className="list-row" key={c.id}><span>{c.firstName} {c.lastName} · {c.className??'No class'}</span><button className="btn-text danger" onClick={async()=>{await parentsApi.unlink(selected.id,c.id);await inspect(selected);}}>Unlink</button></div>)}</div></>:<div className="empty-state">Select “Children” to manage parent–student links.</div>}</div></div>
{open&&<div className="modal-backdrop"><div className="modal-card wide"><h3>{selected?'Edit parent':'Add parent'}</h3><div className="form-grid">{(['firstName','lastName','email','password','address','phoneNumber']as const).map(k=><div className="field" key={k}><label>{k.replace(/([A-Z])/g,' $1')}</label><input type={k==='password'?'password':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>Gender</label><select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>MALE</option><option>FEMALE</option><option>OTHER</option></select></div></div><div className="modal-actions"><button className="btn-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={()=>void save()}>Save</button></div></div></div>}</div>}
